insert into VOITURE(IMMATRICULATION,SURNOM) VALUES('JB007GB','Aston');
insert into VOITURE(IMMATRICULATION,SURNOM) VALUES('CV192ZZ','Titine');



insert into MEMBRE(LOGIN,MOTDEPASSE, SURNOM) VALUES ('A','A','A');
insert into MEMBRE(LOGIN,MOTDEPASSE, SURNOM) VALUES ('B','B','B');



insert into PROJET(INTITULEP,DESCRIPTIONP,DIRIGEPAR_LOGIN) VALUES ('AAR', 'AH LES ENTITIES!' , 'A');
insert into PROJET(INTITULEP,DESCRIPTIONP,DIRIGEPAR_LOGIN) VALUES ('TC', 'AH LES THEATREUX!' , 'B');
insert into PROJET(INTITULEP,DESCRIPTIONP,DIRIGEPAR_LOGIN) VALUES ('DM', 'Fouille de données' , 'B');

INSERT INTO PROJET_MEMBRE(PARTICIPE_INTITULEP,CONTRIBUTIONDE_LOGIN) VALUES ('AAR','B');
--INSERT INTO PROJET_MEMBRE(PARTICIPE_INTITULEP,CONTRIBUTIONDE_LOGIN) VALUES ('TC','A');

INSERT INTO COMPETENCE(INTITULEC, DESCRIPTIONC) VALUES ('COMP1','SAVOIR ECRIRE');
INSERT INTO COMPETENCE(INTITULEC, DESCRIPTIONC) VALUES ('COMP2','SAVOIR LIRE');

INSERT INTO COMPETENCE_PROJET(REQUISEPOUR_INTITULEP,NECESSITE_INTITULEC) VALUES ('TC','COMP1');

INSERT INTO MEMBRE_DECLARE(MEMBRE_LOGIN,DECLARE_KEY,COMMENTAIRE,NIVEAU) VALUES ( 'A', 'COMP1', 'Rapide', 4);